# Generated by Django 2.2.3 on 2019-07-18 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20190625_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='online_users',
            field=models.ManyToManyField(related_name='chat_rooms', related_query_name='chat_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
