# Generated by Django 2.2.3 on 2019-07-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_securityanswer_securityquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestion',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SecurityAnswer',
        ),
        migrations.DeleteModel(
            name='SecurityQuestion',
        ),
    ]
